### ISSUE TITLE
Curiosity: Why was :cd removed?

### ISSUE THREAD

**Issue by BrunoGomesCoelho** [glacambre/shelley#3]
Quick question, wondering why the :cd feature was removed? I know I can just install from a older commit so it's not a problem, just wondering what the rationale was since I use it extensively.

**Comment by glacambre** [comment]
Oh, sorry if I broke this for you - I thought I was the only one using this plugin! The reason I removed working dir synchronization from shelley is that I built another plugin dedicated to this: [syncwd](https://github.com/glacambre/syncwd). From a usage point of view, it works exactly in the same manner as shelley did - you source the plugin in zsh and then the working directory is synchronized every time you `cd` somewhere new. But it has one big advantage: it doesn't rely on python.
I've grown to hate the dependency on python because every time I used a piece of software that changed the python env, shelley would break. Syncwd will keep working as long as neovim is your $PATH, which much nicer IMO :).

**Comment by BrunoGomesCoelho** [comment]
No problem, I just added the previous commit # to Plug and it's working as before - I've been using it for the past 10 months and find it really useful! Used to have a hacky workaround with pwd/xclip before.

Will port to syncwd when I get the time (I don't use nvim in my path and instead alias vim to nvim - old habits die hard), the python dependency thing makes sense. Thanks for the good plugin!
